#ifndef IOCTL_H
#define IOCTL_H

#include <ntddk.h>
#include <wdf.h>

// Device Type (Unknown = 0x22 is standard for 3rd party)
#define FILE_DEVICE_ARAKNE  0x00008000

// Maximum whitelist entries
#define MAX_WHITELIST_ENTRIES 64
#define MAX_PROCESS_NAME_LEN  64

// Function Codes (0x800 - 0xFFF are reserved for customers)
#define IOCTL_ARAKNE_PING              CTL_CODE(FILE_DEVICE_ARAKNE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARAKNE_TERMINATE_PROCESS CTL_CODE(FILE_DEVICE_ARAKNE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARAKNE_NETWORK_ISOLATE   CTL_CODE(FILE_DEVICE_ARAKNE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARAKNE_NUKE_MODE         CTL_CODE(FILE_DEVICE_ARAKNE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARAKNE_SELF_DEFENSE      CTL_CODE(FILE_DEVICE_ARAKNE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARAKNE_ETW_SUBSCRIBE     CTL_CODE(FILE_DEVICE_ARAKNE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ARAKNE_SET_WHITELIST     CTL_CODE(FILE_DEVICE_ARAKNE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Structures for IOCTL Input

typedef struct _ARAKNE_TERMINATE_REQUEST {
    ULONG ProcessId;
} ARAKNE_TERMINATE_REQUEST, *PARAKNE_TERMINATE_REQUEST;

typedef struct _ARAKNE_SELF_DEFENSE_REQUEST {
    ULONG ProtectionLevel; // 1 = On, 0 = Off
    ULONG ProtectedPID;    // PID of Arakne.exe
} ARAKNE_SELF_DEFENSE_REQUEST, *PARAKNE_SELF_DEFENSE_REQUEST;

typedef struct _ARAKNE_NETWORK_REQUEST {
    BOOLEAN Isolate; // TRUE = Cut Internet
} ARAKNE_NETWORK_REQUEST, *PARAKNE_NETWORK_REQUEST;

// Whitelist entry - process name (lowercase)
typedef struct _ARAKNE_WHITELIST_ENTRY {
    WCHAR ProcessName[MAX_PROCESS_NAME_LEN]; // e.g., L"svchost.exe"
} ARAKNE_WHITELIST_ENTRY, *PARAKNE_WHITELIST_ENTRY;

// Whitelist request - array of safe processes
typedef struct _ARAKNE_WHITELIST_REQUEST {
    ULONG EntryCount;
    ARAKNE_WHITELIST_ENTRY Entries[MAX_WHITELIST_ENTRIES];
} ARAKNE_WHITELIST_REQUEST, *PARAKNE_WHITELIST_REQUEST;

#endif // IOCTL_H
